Drop Symfony 2.1 support
benja-M-1/BGObjectRoutingBundle pull request #5
Opened 2017-03-31 15:11 UTC by mpdude

2017-03-31 17:38 UTC, mpdude commented
Wait, will be pushing more commits.

@benja-M-1 what's the best way to notify you? Are you watching this repo?

2017-06-03 22:16 UTC, mpdude commented
*ping* @benja-M-1

2017-06-06 05:52 UTC, benja-M-1 requested changes

2017-06-06 05:52 UTC, benja-M-1 commented on Resources/config/services.xml
> +        <service id="bg_object_routing.adapter.symfony_22" class="JMS\ObjectRouting\Symfony\Symfony22Adapter" public="false">
@mpdude can you use a parameter instead to stay consistent with the rest of the code? You can replace ```bg_object_routing.adapter.symfony_21.class``` by yours.

Thanks

2017-06-06 06:08 UTC, mpdude commented on Resources/config/services.xml
> +        <service id="bg_object_routing.adapter.symfony_22" class="JMS\ObjectRouting\Symfony\Symfony22Adapter" public="false">
I removed the parameter as it was my understanding that this approach was a mistake during the early days of Symfony that has meanwhile been discouraged.

But I will change it later if you'd like to keep it.

2017-06-06 07:57 UTC, mpdude commented
@benja-M-1 updated

2017-06-06 11:19 UTC, merged

2017-06-06 11:21 UTC, benja-M-1 commented
Thanks @mpdude

2017-06-06 11:28 UTC, mpdude commented
Thank you!

Could you tag a new minor release please?